services:
  - type: web
    name: django-web
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --workers=2 --threads=4 --timeout=60
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: REDIS_URL
        fromService:
          type: redis
          name: myredis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString

  - type: worker
    name: celery-worker
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core worker --loglevel=info
    envVars:
      - key: DJANGO_SECRET_KEY
        fromService:
          type: web
          name: django-web
          envVarKey: DJANGO_SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: REDIS_URL
        fromService:
          type: redis
          name: myredis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString

  - type: worker
    name: celery-beat
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: celery -A core beat --loglevel=info
    envVars:
      - key: DJANGO_SECRET_KEY
        fromService:
          type: web
          name: django-web
          envVarKey: DJANGO_SECRET_KEY
      - key: DEBUG
        value: "False"
      - key: REDIS_URL
        fromService:
          type: redis
          name: myredis
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString

databases:
  - name: mydb
    plan: free

  - type: redis
    name: myredis
    plan: free
