# Generated by Django 5.2.4 on 2025-08-25 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='booking_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='end_time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='start_time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='category',
            field=models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Rooftop', 'Rooftop')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='is_available_now',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='price_per_hour',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='eventplace',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Review'), ('inactive', 'Inactive')], db_index=True, default='pending', help_text='Current status of the event place listing (e.g., active, pending review, inactive).', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='meetingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('meeting_request', 'Meeting Request'), ('meeting_response', 'Meeting Response'), ('announcement', 'Announcement'), ('booking_cancellation', 'Booking Cancellation'), ('booking_update', 'Booking Update')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='furnished',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Villa', 'Villa'), ('Apartment', 'Apartment')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Rent', 'Rent')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['event_place', 'booking_date', 'status'], name='users_event_event_p_444031_idx'),
        ),
        migrations.AddIndex(
            model_name='eventbooking',
            index=models.Index(fields=['user', '-booked_at'], name='users_event_user_id_02b717_idx'),
        ),
        migrations.AddIndex(
            model_name='eventplace',
            index=models.Index(fields=['category', 'is_available_now', 'price_per_hour'], name='users_event_categor_b7a46b_idx'),
        ),
        migrations.AddIndex(
            model_name='eventplace',
            index=models.Index(fields=['status', '-created_at'], name='users_event_status_e04353_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrequest',
            index=models.Index(fields=['property', '-requested_at'], name='users_meeti_propert_9a9abe_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrequest',
            index=models.Index(fields=['status', '-requested_at'], name='users_meeti_status_26caf9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', '-created_at'], name='users_notif_user_id_f3f50a_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location', 'property_type'], name='users_prope_locatio_c041f2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', '-created_at'], name='users_prope_status_6af015_idx'),
        ),
        migrations.AddIndex(
            model_name='savedproperty',
            index=models.Index(fields=['user', '-saved_at'], name='users_saved_user_id_c0bfce_idx'),
        ),
    ]
